show:
    path:     /
    defaults: { _controller: DimaBatteriesBundle:Batteries:show }

add:
    path:     /add
    defaults: { _controller: DimaBatteriesBundle:Batteries:add }

reset:
    path:     /reset
    defaults: { _controller: DimaBatteriesBundle:Batteries:reset }
