<?php

namespace Dima\BatteriesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BatteryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatteryRepository extends EntityRepository
{
    public function findAllGroupedByType()
    {
        return $qb = $this->createQueryBuilder('b')
            ->select('b.type, count(b.id) AS num')
            ->groupBy('b.type')
            ->getQuery()
            ->getResult();
    }
}
