Dima\BatteriesBundle\Entity\Battery:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: string
            length: 255
        owner:
            type: string
            length: 255
    lifecycleCallbacks: {  }
